Numpy Array Operations:   


In [25]:
#1. Create a 1D NumPy Array: 

import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print (temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [26]:
# 2. Inspection and Properties:

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print (temperatures_w1.shape)
print(temperatures_w1.size)
print(temperatures_w1.dtype)


(7,)
7
float64


In [27]:
# 3. Array Operations:
# ● Find the maximum, minimum, and mean temperatures for the week.

temperatures_w1_f = (temperatures_w1 * 9/5) + 32
print(temperatures_w1_f)

print(np.max(temperatures_w1_f))
print(np.min(temperatures_w1_f))
print(np.mean(temperatures_w1_f))

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
78.98
69.44
74.37714285714286


In [28]:
# 4. Array Slicing and Indexing:
print(temperatures_w1[0:3])
print(temperatures_w1[-2:])
print(temperatures_w1[2:5])

[22.5 25.3 20.8]
[24.8 21.9]
[20.8 23.4 26.1]


In [30]:
# 5. Create a 2D Array:

temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [31]:
# 6. Inspect and Slice the 2D Array: 

print (temperatures.shape)
print(temperatures.size)
print(temperatures.dtype)



(2, 7)
14
float64


In [32]:
# Extract the temperatures for each week and the weekends (last two days) for both weeks.
week_1 = temperatures[0, :]
week_2 = temperatures[1, :]
weekends = temperatures[:, -2:]

print(week_1)
print(week_2)
print(weekends)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
[19.2 22.5 21.3 24.  23.5 22.8 20.1]
[[24.8 21.9]
 [22.8 20.1]]


Pandas Series:  